env:
  TERM: xterm-256color

window:
  decorations: none
  dynamic_padding: false
  padding:
    x: 5
    y: 1

scrolling:
  history: 5000
  multiplier: 3

font:
  draw_bold_text_with_bright_colors: false
  offset:
    x: 1
  size: 12.0
  normal:
    family: JetBrains Mono
    style: Regular
  bold:
    family: JetBrains Mono
    style: Regular
  italic:
    family: JetBrains Mono
    style: Regular Italic
  bold_italic:
    family: JetBrains Mono
    style: Regular Italic

cursor:
  style: Beam

live_config_reload: true

hints:
  launcher: open

