env:
  TERM: xterm-256color

window:
  decorations: none
  dynamic_padding: false
  padding:
    x: 5
    y: 1

scrolling:
  history: 5000
  multiplier: 3

font:
  draw_bold_text_with_bright_colors: false
  offset:
    x: 1
  size: 12.0
  normal:
    family: JetBrains Mono
    style: Regular
  bold:
    family: JetBrains Mono
    style: Bold
  italic:
    family: JetBrains Mono
    style: Regular Italic
  bold_italic:
    family: JetBrains Mono
    style: Bold Italic

cursor:
  style: Beam

live_config_reload: true

hints:
  launcher: open

colors:
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2' 
  normal:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xbd93f9'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xbbbbbb'
  bright:
    black:   '0x555555'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xcaa9fa'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xffffff'
