live_config_reload = true

[env]
TERM = "xterm-256color"

[cursor]
style = "Beam"

[font]
size = 12

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
decorations = "none"

# Default colors
[colors.primary]
background = '0x1E1E1E'
foreground = '0xD4D4D4'

# Normal colors
[colors.normal]
black =   '0x1E1E1E'
red =     '0xF44747'
green =    '0x608B4E'
yellow =  '0xD7BA7D'
blue =    '0x569CD6'
magenta = '0xC586C0'
cyan =    '0x9CDCFE'
white =   '0xD4D4D4'