tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"
tap "teamookla/speedtest"

brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

brew 'coreutils'
brew 'findutils'
brew 'bash'
brew 'grep'
brew 'tree'
brew 'wget'
brew 'curl'
brew 'git'
brew 'git-extras'
brew 'python'
brew 'ansible'
brew 'sshuttle'
brew 'vim'
brew 'watch'
brew 'mas'
brew 'tldr'
brew 'unrar'
brew 'awscli'
brew 'node'
brew 'jq'
brew 'diff-so-fancy'
brew 'tmux'
brew 'irssi'
brew 'reattach-to-user-namespace'
brew 'gnu-getopt'
brew 'bat'
brew 'terraform'
brew 'dive'
brew 'telnet'
brew 'tree'
brew 'speedtest'
brew 'awk'
brew 'newsboat'
brew 'starship'
brew 'lf'
brew 'kubectl'
brew 'eksctl'
brew 'kubectx'
brew 'minikube'
brew 'k9s'

#cask_args appdir: '/Applications'
#cask 'amazon-workspaces'
#cask 'appcleaner'
#cask 'docker'
#cask 'google-drive-file-stream'
#cask 'iterm2'
#cask 'macdown'
#cask 'transmission'
#cask 'telegram'
#cask 'spotify'
#cask 'slack'
#cask 'transmit'
#cask 'visual-studio-code'
#cask 'viscosity'
#cask 'textual'
#cask 'firefox'
#cask 'fanny'
#cask 'sequel-pro'

#cask 'font-jetbrains-mono'

#mas 'Pixelmator', id:407963104
#mas 'Amphetamine', id:937984704
