tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"

brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'coreutils'
brew 'findutils'
brew 'grep'
brew 'tree'
brew 'wget'
brew 'curl'
brew 'git'
brew 'python'
brew 'ansible'
brew 'vim'
brew 'watch'
brew 'awscli'
brew 'jq'
brew 'tmux'
brew 'terraform'
brew 'terraform-ls'
brew 'telnet'
brew 'tree'
brew 'awk'
brew 'newsboat'
brew 'kubectl'
brew 'kubectx'
brew 'sceptre'
brew 'node'
brew 'aws-cdk'
brew 'helm'
brew 'irssi'

# cask 'font-jetbrains-mono'
# cask 'firefox'
# cask 'rectangle'
# cask 'scroll-reverser'
# cask 'spotify'
# cask 'visual-studio-code'
# cask 'docker'
# cask 'mouse-fix'
# cask 'obsidian'
# cask 'slack' 
