k9s:
  liveViewAutoRefresh: true
  gpuVendors: {}
  screenDumpDir: /Users/mijndert/Library/Application Support/k9s/screen-dumps
  refreshRate: 2
  apiServerTimeout: 15s
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  portForwardAddress: localhost
  ui:
    skin: catppuccin-mocha
    enableMouse: false
    headless: false
    logoless: true
    crumbsless: false
    splashless: true
    reactive: false
    noIcons: false
    defaultsToFullScreen: false
    useFullGVRTitle: false
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.37
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    disableAutoscroll: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  defaultView: ""
